hashcat/hashcat

- docs/changes.txt
- src/oclHashcat.c
It is a problem specific to nvidia, problem did not affect mask attacks but possibly all other attack modes.
This shows where the problem relies and proposes a possible fix for it. Please review.
Tested with success on gtx 980 ti.
(btw: driver version should be irrelevant)
> for issue #1: cuMemsetD8() 1 error

- src/Makefile
it should read "scrypt" not "script"
cosmetic fix only
> typo fixed in Makefile

- include/shared.h
- include/types.h
- src/oclHashcat.c
- src/shared.c
The goal of this pull request is to implement the enhancement mentioned in issue #10: an user should be allowed to press a hotkey (in this case 'c') to tell oclHashcat that it should stop right after the next restore point was reached (and also saved to the .restore file).
This feature should work whenever --restore-disable was not set.
oclHashcat will continue cracking until the next restore point was reached, after that it will stop cracking with status code "aborted" (2).
Please review. Thx
> implements the enhancement mentioned in issue #10 (cancel on next checkpoint)

- src/oclHashcat.c
- src/shared.c
This is just an additional small feature to issue #10: also allow the user to disable a restore point monitoring check, i.e. with this extra feature the user can do both create a new check or disable the check if it is already there (but the user does not want it anymore).
Thx
> allow both enabling and disabling of restore point update (implemented with issue #10)

- docs/BUILD.md
- src/Makefile
- tools/deps.sh
This commit fixes issue #14, remove the dependency on the /opt/ folder (which can only be modified by root users under linux).
(P.S.: We should do the same for hashcat)
> issue #14: move /opt/hashcat-deps/ to [git_clone_dir]/hascat-deps/

- include/common.h
- include/ext_ADL.h
- include/ext_dummy.h
- include/ext_nvapi.h
- include/ext_nvml.h
- include/ext_smi.h
- include/shared.h
- include/types.h
- src/oclHashcat.c
- src/shared.c
one problem that is still there since last commit: dynamic loading of libnvidia-ml)
The remaining parts should be back and working (but untested because of the lib loading problem).
This commit tries to reenable all the fan control and hardware monitoring features (including aborting when the GPU temperature is too high).
> fixed hardware monitor for amd/nv

- include/ext_nvml.h
- include/shared.h
- src/Makefile
- src/ext_nvml.c
- src/oclHashcat.c
- src/shared.c
This only happens on nvidia systems (systems with nvidia GPUS installed), libnvidia-ml will now load dynamically if the system is running posix and has Nvidia installed.
We had to do this change because otherwise even AMD users need to have libnvidia-ml on there system (and in that case it would get loaded too even if not necessary).
> change in library loading: libnvidia-ml now does load dynamically

- src/oclHashcat.c
There was a slight memory problem (especially noticeable when using --benchmark with all default algos). errors of type -4 etc should not occur anymore.
Thx
> fix OpenCL memory problem (exhaustion): -4 error should be gone

- src/shared.c
- tools/test.pl
The parser (and tests) of oclHashcat did not enforce the limit for -m 22 = Juniper Netscreen/SSG (ScreenOS) to length 10. This is needed since we have a salt buffer of length 32 and we always need to append 22 characters to the salt (":Administration Tools:").
Thx
> limit the salt length of -m 22 = Juniper Netscreen/SSG (ScreenOS) to 10

- src/oclHashcat.c
There was a minor typo/display problem in the usage (--help output).
The same problem was fixed within a commit in cpu hashcat (PR): https://github.com/philsmd/hashcat/commit/98028bd6a0dd4ea3e1ccc963a8bb3c8a9516fca9
Thx
> fixed minor display problem in usage

- docs/BUILD.md
- src/Makefile
- tools/deps.sh
The NVML lib is dynamically loaded on Nvidia systems, therefore there is no need (anymore) that the devs install it on the dev system (the required library ships with the driver anyway).
Thanks
> issue #38: NVIDIA SDK is not needed anymore

- extra/tab_completion/howto.txt
- extra/tab_completion/install
- extra/tab_completion/oclHashcat.sh
Since we now allow the user to use "sudo make install", tab-completion had to be updated to work also with just "oclHashcat ..." in the command line.
This patch addresses this problem and in addition to that it changes the name of the bash complete script to "oclHashcat.sh" (was oclHashcat64.bin) such that it is more clear that this script works for all three variants: oclHashcat64.bin, oclHashcat32.bin and oclHashcat
Thx
> fixed tab completion to work with 64.bin, 32.bin and just oclHashcat binaries

- tools/deps.sh
there was a typo in tools/deps.sh introduced with: dc13c2fc71c8c9e3af66ceaa9dfc8ff34cb56bfb
The folder name should be "adl-sdk" and not "adl-sdk*".
Thanks
> fixed typo in tools/deps.sh

- extra/tab_completion/oclHashcat.sh
The tab completion script (extra/tab_completion/oclHashcat.sh) was not 100% up-to-date. This patch should fix that: there were some algorithm missing in the algorithm list, some long options with parameters were not listed + ./oclHashcat should also trigger tab completion (not only "oclHashcat" should work but also "./oclHashcat").
> updated tab completion with current algorithm list etc

- include/shared.h
- src/oclHashcat.c
- src/shared.c
The problem was that it wasn't very clear that e.g. ~/.hashcat/oclHashcat/ is the (default) session folder or if I use --session abc that the sessions are located under ~/.hashcat/abc/.
With this patch the sessions are located under ~/.hashcat/sessions/ . This should be much more easy to understand what this folder is used for.
Under this folder (~/.hashcat/sessions/) there will be placed files such as $session.pot, $session.restore, $session.log etc
Thanks
> this patch makes it much clearer where sessions under ~/.hashcat are located

- .gitignore
this patch just updates the .gitignore file such that files in deps/, kernels/ and the new binary "oclHashcat" are ignored by i.e. "git status".
(note: the ** does ignore files with 0 to indefinite depth, so we do *NOT* need both deps/* and deps**) 
Thanks
> minor: .gitignore update

- tools/test.pl
Since we did replace ./oclHashcat64.bin with ./oclHashcat kind of everywhere in the source code, I suggest that we also should update tools/test.pl s.t. the native binary "oclHashcat" is used there too.
Thanks
> using oclHashcat instead of oclHashcat64.bin also in tools/test.pl

- example0.sh
- example400.sh
- example500.sh
- tools/package_bin.sh
Only when we use the packaging script we need to rewrite the commands such that the 64.bin version is used.
This allows us to use "oclHashcat" within the example*.sh on git but when we build the binary package (.7z for hashcat.net/oclHashcat ) we use "oclHashcat64.bin".
This way, the user can simply clone the repo, use "make" to build the project and hence the oclHashcat binary and after that he can execute e.g. ./example0.sh without any error.
> the example*.sh files should now also use the native binary

- docs/BUILD.md
This patch just updates BUILD.md . There are 2 major changes:
1. removed some target that do not exist anymore (and replaced them with the new targets if possible)
2. added a note about the need to clone OpenCL-Headers for "make binaries"
The reason is that make binaries needs the OpenCL-Headers s.t. e.g. windows binaries can be cross-compiled. This fix adds a note about OpenCL-Headers, explains how to clone it and also mentions the reason why tools/deps.sh does not automatically clone it.
Thx
> update for the build instructions with the notes about OpenCL-Headers

- docs/BUILD.md
this additional section within BUILD.md should address the problem on how to fix the 'cannot find -lOpenCL' error when using the "binaries" Makefile 
For the 32-bit version we have no libOpenCL.so (furthermore: in general we do not need it; for native compilation). This patch adds a note on how to get rid of the error message by suggesting a "ln -s" symbolic link to libOpenCL.so.1
thanks
> added note about how to fix the 'cannot find -lOpenCL' error to BUILD.md

- tools/rules_test/Makefile
We do not need the .cpp extension anymore.
The Makefile failed because the file (*.cpp) was replaced by the ansi c version (*.c).
Unfortunately, the Makefile was not up-to-date. This patch should allow the user to make the gpu2cpu_rule_test binary (again).
Thx
> updated gpu2cpu_rule_test script, we do not need the c++ here

- src/Makefile
I think it makes sense to also install the example scripts example0.sh, example400.sh and example500.sh into the document folder (defaults to /usr/local/share/doc/oclHashcat/).
This way the user can easily find some useful examples on how to run oclHashcat.
> install also the example scripts, place them into the doc folder

- src/Makefile
Pull request #53 did not correctly copy the *.hash and *.dict files to the doc folder. They are both needed to successfully run the tests.
> pr #53 did not copy the example .hash and .dict files to the doc folder

- extra/tab_completion/install
- extra/tab_completion/oclHashcat.sh
This commit just updated the tab completion script.
It checks whether the old "oclHashcat64.bin" is still present and if so removes it.
Tab completion was also added to the --opencl-platform option.
> updated tab completion

- docs/license.txt
This pull request just updated the year within the MIT license file.
I did try to find other occurences of "2015", i.e. years that must be updated, but besides this one didn't find any other. We should be good with this fix.
Thanks
> updated MIT license year

- src/oclHashcat.c
This additional check rejects every --opencl-platform value that is larger than the number of acutal OpenCL platform.
Currently, there is no check about what (--opencl-platform) values are specified by the user and therefore the --opencl-platform value was silently ignored whenever the number of OpenCL platforms was for instance exactly 1 (only 1 GPU for example).
Thx
> added --opencl-platform check, reject numbers > number of OpenCL platforms

- OpenCL/m21420_a0-pure.cl
- src/modules/module_21420.c
This patch implements a pure `sha256($salt.sha256_bin($pass))` kernel, as used in Bitcoin (P2WSH addresses). It is envisioned that `$salt` will be set to `0x0020` and `$pass` to the candidate redeem script, with converted Bech32 address used as hashes. However, it may also have other uses.
> Implement sha256($salt.sha256_bin($pass)) kernel
